#!/usr/bin/env node
// Emits typed address books from a deployment JSON so no downstream code hardcodes
// an address. Usage: node ops/codegen.mjs [deployments/arc-testnet.json]
// Run after every deploy; extend TARGETS as backend and mobile consumers land.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const inputArg = process.argv[2] ?? "deployments/arc-testnet.json";
const d = JSON.parse(readFileSync(resolve(repoRoot, inputArg), "utf8"));

const banner = `// GENERATED by ops/codegen.mjs from ${inputArg}. Do not edit by hand.`;

const TARGETS = [
  {
    path: "engine/src/addresses.ts",
    render: () =>
      `${banner}
export const chainId = ${d.chainId};

export const addresses = {
  usdc: "${d.usdc}",
  policyRegistry: "${d.policyRegistry}",
  yieldAdapter: "${d.yieldAdapter}",
  escrow: "${d.escrow}",
  settlementVault: "${d.settlementVault}",
} as const;

export type ContractName = keyof typeof addresses;
`,
  },
];

for (const t of TARGETS) {
  const out = join(repoRoot, t.path);
  writeFileSync(out, t.render());
  console.log(`wrote ${t.path}`);
}
