#!/usr/bin/env node
// Emits typed address books from a deployment JSON so no downstream code hardcodes
// an address. Usage: node ops/codegen.mjs [deployments/arc-testnet.json]
// Run after every deploy; extend TARGETS as backend and mobile consumers land.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const inputArg = process.argv[2] ?? "deployments/arc-testnet.json";
const d = JSON.parse(readFileSync(resolve(repoRoot, inputArg), "utf8"));
const arcConfig = JSON.parse(
  readFileSync(resolve(repoRoot, "deployments/arc-config.json"), "utf8"),
);

if (d.chainId !== arcConfig.chainId) {
  throw new Error("Deployment and Arc configuration chain IDs do not match");
}

const banner = `// GENERATED by ops/codegen.mjs from ${inputArg}. Do not edit by hand.`;

const TARGETS = [
  {
    path: "engine/src/addresses.ts",
    render: () =>
      `${banner}
export const chainId = ${d.chainId};

export const addresses = {
  usdc: "${d.usdc}",
  policyRegistry: "${d.policyRegistry}",
  yieldAdapter: "${d.yieldAdapter}",
  escrow: "${d.escrow}",
  settlementVault: "${d.settlementVault}",
} as const;

export type ContractName = keyof typeof addresses;
`,
  },
  {
    path: "mobile/Recourse/Generated/Deployment.swift",
    render: () =>
      `${banner}
import Foundation

enum Deployment {
    static let rpcURL = "${arcConfig.rpcUrl}"
    static let chainID: UInt64 = ${d.chainId}
    static let usdc = "${d.usdc}"
    static let policyRegistry = "${d.policyRegistry}"
    static let yieldAdapter = "${d.yieldAdapter}"
    static let escrow = "${d.escrow}"
    static let settlementVault = "${d.settlementVault}"
    static let attestor = "${d.attestor}"
    static let treasury = "${d.treasury}"
}
`,
  },
];

for (const t of TARGETS) {
  const out = join(repoRoot, t.path);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, t.render());
  console.log(`wrote ${t.path}`);
}
