#!/usr/bin/env node
// Emits typed address books from a deployment JSON so no downstream code hardcodes
// an address. Usage: node ops/codegen.mjs [deployments/arc-testnet.json]
// Run after every deploy; extend TARGETS as backend and mobile consumers land.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const inputArg = process.argv[2] ?? "deployments/arc-testnet.json";
const d = JSON.parse(readFileSync(resolve(repoRoot, inputArg), "utf8"));
const arcConfig = JSON.parse(
  readFileSync(resolve(repoRoot, "deployments/arc-config.json"), "utf8"),
);

// A deployment file that carries its own endpoint is self describing and needs no
// second file. arc-config.json predates that and still supplies testnet's.
const rpcUrl = d.rpcUrl ?? arcConfig.rpcUrl;
if (!rpcUrl) throw new Error(`${inputArg} has no rpcUrl and arc-config.json does not cover chain ${d.chainId}`);

// The FX venue is deployed separately from the escrow, so it has its own file and is
// optional. Loaded only when it belongs to the chain being generated: a testnet pool
// wired into a mainnet build would offer real money a venue holding play money.
let fx = null;
try {
  const candidate = JSON.parse(readFileSync(resolve(repoRoot, "deployments/arc-testnet-fx.json"), "utf8"));
  if (candidate.chainId === d.chainId) fx = candidate;
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}

// Whether this chain carries the buyer protection contracts. False on Arc mainnet,
// where holding, sending and receiving need none of them and Circle has not whitelisted
// the settlement vault for USYC. The same distinction the backend draws, by the same
// name, so the two agree about what a chain is.
const consumer = Boolean(d.escrow && d.policyRegistry && d.settlementVault);
// Treasuries are a separate protocol with its own deploy, so a chain can carry the
// consumer contracts without it or neither. Arc mainnet has neither yet.
const olienFactory = d.olien?.factory ?? null;
const ZERO = "0x0000000000000000000000000000000000000000";
// Zero rather than absent, because twenty call sites read these without validating
// them and only the features that would call a contract need to care. Those check
// `consumer` instead.
const escrow = d.escrow ?? ZERO;
const policyRegistry = d.policyRegistry ?? ZERO;
const settlementVault = d.settlementVault ?? ZERO;
const yieldAdapter = d.yieldAdapter ?? ZERO;
const attestor = d.attestor ?? ZERO;
const treasury = d.treasury ?? ZERO;

const banner = `// GENERATED by ops/codegen.mjs from ${inputArg}. Do not edit by hand.`;

const TARGETS = [
  {
    path: "engine/src/addresses.ts",
    render: () =>
      `${banner}
export const chainId = ${d.chainId};

export const addresses = {
  usdc: "${d.usdc}",
  policyRegistry: "${policyRegistry}",
  yieldAdapter: "${yieldAdapter}",
  escrow: "${escrow}",
  settlementVault: "${settlementVault}",
} as const;

export type ContractName = keyof typeof addresses;
`,
  },
  {
    path: "mobile/Recourse/Generated/Deployment.swift",
    render: () =>
      `${banner}
import Foundation

enum Deployment {
    static let rpcURL = "${rpcUrl}"
    static let chainID: UInt64 = ${d.chainId}
    static let usdc = "${d.usdc}"
    static let policyRegistry = "${policyRegistry}"
    static let yieldAdapter = "${yieldAdapter}"
    static let escrow = "${escrow}"
    static let settlementVault = "${settlementVault}"
    static let attestor = "${attestor}"
    static let treasury = "${treasury}"
    /// Whether this chain carries the buyer protection contracts. False on Arc
    /// mainnet, where the four addresses above are zero and any screen that would
    /// call one must say so rather than call it.
    static let consumer = ${consumer}
    /// The Olien factory, when treasuries exist on this chain. Nil means the treasury
    /// routes would answer that the service is off, so Teams says it is coming instead
    /// of showing that sentence to someone.
    static let olienFactory: String? = ${olienFactory ? `"${olienFactory}"` : "nil"}
${fx ? `
    // FX venue, deployed separately. See deployments/arc-testnet-fx.json.
    static let fxRouter: String? = "${fx.router}"
    static let eurc: String? = "${fx.eurc}"
    /// Whether the venue is deep enough to put in front of someone. A venue can be
    /// deployed and still refuse every ordinary amount, which is worse than not
    /// offering it, so this is a separate fact from whether it exists.
    static let fxPublic = ${fx.public === true}` : `
    static let fxRouter: String? = nil
    static let eurc: String? = nil
    static let fxPublic = false`}
}
`,
  },
];

for (const t of TARGETS) {
  const out = join(repoRoot, t.path);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, t.render());
  console.log(`wrote ${t.path}`);
}
